version: '3.7'

services:
  proxy:
    build: ./
    volumes:
      - ./proxy_conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    restart: always
    networks:
      - wp_net

  wordpress1_db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./website_data/wordpress1_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wp_net


  wordpress1:
    image: wordpress:latest
    container_name: 'wordpress1'
    restart: always
    volumes:
      - ./website_data/wordpress1_uploads:/var/www/html/wp-content/uploads
      - ./website_data/wordpress1_themes:/var/www/html/wp-content/themes
      - ./website_data/wordpress1_plugins:/var/www/html/wp-content/plugins
    depends_on:
      - wordpress1_db
    environment:
      WORDPRESS_DB_HOST: wordpress1_db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wp_net

        
  wordpress2_db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./website_data/wordpress2_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wp_net


  wordpress2:
    image: wordpress:latest
    container_name: 'wordpress2'
    restart: always
    volumes:
      - ./website_data/wordpress2_uploads:/var/www/html/wp-content/uploads
      - ./website_data/wordpress2_themes:/var/www/html/wp-content/themes
      - ./website_data/wordpress2_plugins:/var/www/html/wp-content/plugins
    depends_on:
      - wordpress2_db
    environment:
      WORDPRESS_DB_HOST: wordpress2_db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wp_net

networks:
  wp_net:
    driver: bridge
